### ISSUE TITLE
Generating an app with 21-Points JDL results in errors

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#143]
**Describe the bug**

If I try to generate an app with [`21-points.jh`](https://github.com/jhipster/jdl-samples/blob/main/21-points.jh), it results in an error.

**To Reproduce**

```
jhipster jdl 21-points.jh --blueprints quarkus
```

I'm guessing this happens because Quarkus doesn't have support for Elasticsearch yet.

```
The entity Preferences is being updated.

Git repository initialized.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Copying template quarkus/src/main/java/package/web/rest/EntityResource.java.ejs failed. [ReferenceError: /Users/mraible/generator-jhipster-quarkus/generators/entity-server/templates/quarkus/src/main/java/package/web/rest/EntityResource.java.ejs:60
    58| <%_ if (searchEngine === 'elasticsearch') { _%>
    59|
 >> 60| <%- include('../../_partials/imperative/web/search', this); -%>
    61| <%_ } _%>
    62| }
    63|

/Users/mraible/generator-jhipster-quarkus/generators/entity-server/templates/quarkus/src/main/java/package/_partials/imperative/web/search.ejs:34
    32|     @GET
    33|     @Path("/_search/<%= entityApiUrl %>")
 >> 34| <%- include('../common/search', this); -%>
    35|

/Users/mraible/generator-jhipster-quarkus/generators/entity-server/templates/quarkus/src/main/java/package/_partials/imperative/common/search.ejs:27
    25|         log.debug("REST request to search for a page of <%= entityClassPlural %> for query {}", query);<% if (viaService) { %>
    26|         Page<<%= entityOrDtoClass %>> page = <%= entityInstance %>Service.search(query, pageable);<% } else { %>
 >> 27|         Page<<%= asEntity(entityClass) %>> page = <%= entityInstance %>SearchRepository.search(queryStringQuery(query), pageable);<% } %>
    28|         HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(<% if (!reactive) { %>ServletUriComponentsBuilder.fromCurrentRequest()<% } else { %>UriComponentsBuilder.fromHttpRequest(request)<% } %>, page);
    29|         return ResponseEntity.ok().headers(headers).body(<% if (!viaService && dto === 'mapstruct') { %><%= entityToDtoMethodInvocation %>(<% } %>page.getContent()<% if (!viaService && dto === 'mapstruct') { %>)<% } %>);
    30|     <% } -%>

asEntity is not defined]
    at module.exports.error (/Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/generators/generator-base.js:1590:15)
    at /Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/generators/utils.js:256:23
    at tryHandleCache (/Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:275:14)
    at Object.exports.renderFile (/Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:489:10)
    at Object.renderContent (/Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/generators/utils.js:252:9)
    at module.exports.template (/Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/generators/generator-base-private.js:769:23)
    at /Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/generators/generator-base.js:2040:42
    at Array.forEach (<anonymous>)
    at module.exports.writeFilesToDisk (/Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/generators/generator-base.js:2002:45)
    at module.exports.writeServerFiles (/Users/mraible/generator-jhipster-quarkus/generators/entity-server/files.js:343:18)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (/Users/mraible/generator-jhipster-quarkus/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1007:20)
    at processImmediate (internal/timers.js:461:21)
INFO! App: child process exited with code 1
ERROR! JHipster finished with code 1
```

If I remove `searchEngine elasticsearch`, it generates successfully. 

However, if I try to run it, I get an error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mraible/quarkus/build.gradle' line: 188

* What went wrong:
A problem occurred evaluating root project 'health-points'.
> Could not get unknown property 'wiremock_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by mraible** [comment]
Elasticsearch support issue at https://github.com/jhipster/generator-jhipster-quarkus/issues/80.
