### ISSUE TITLE
Protractor tests fail when using blog-oauth2 JDL (without entities)

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#145]
**Describe the bug**

If you generate an app with the JDL below, some Protractor tests fail:

```
application {
  config {
    baseName blog,
    applicationType monolith,
    authenticationType oauth2,
    packageName com.jhipster.demo.blog,
    prodDatabaseType mysql,
    cacheProvider hazelcast,
    buildTool maven,
    clientFramework angular,
    testFrameworks [protractor]
  }
}
```

**To Reproduce**

Copy the JDL above to a `blog-oauth2.jdl` file, then run:

```
jhipster jdl blog-oauth2.jdl --blueprints quarkus
```

Start the app with `./mvnw`, then run `npm run e2e` in a separate terminal window. A couple of the tests fail.

```
> blog@0.0.1-SNAPSHOT e2e /Users/mraible/quarkus
> protractor src/test/javascript/protractor.conf.js

[09:22:42] W/configParser - pattern ./e2e/entities/**/*.spec.ts did not match any files.
[09:22:42] I/launcher - Running 1 instances of WebDriver
[09:22:42] I/direct - Using ChromeDriver directly...


  account
    ✓ should fail to login with bad password
    ✓ should login successfully with admin account
    ✓ should navigate to 404 not found error page on non existing route and show user own navbar if valid authentication exists

  administration
    ✓ should load metrics
    ✓ should load health
    1) should load configuration
    ✓ should load audits
    2) should load logs


  6 passing (9s)
  2 failing

  1) administration
       should load configuration:
     NoSuchElementError: No element found using locator: By(css selector, *[id="configuration-page-heading"])
      at /Users/mraible/quarkus/node_modules/protractor/built/element.js:814:27
      at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.<computed> [as getAttribute] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.<computed> [as getAttribute] (node_modules/protractor/built/element.js:831:22)
      at /Users/mraible/quarkus/src/test/javascript/e2e/admin/administration.spec.ts:38:101
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/tslib/tslib.js:111:62)

  2) administration
       should load logs:
     NoSuchElementError: No element found using locator: By(css selector, *[id="logs-page-heading"])
      at /Users/mraible/quarkus/node_modules/protractor/built/element.js:814:27
      at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.<computed> [as getAttribute] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.<computed> [as getAttribute] (node_modules/protractor/built/element.js:831:22)
      at /Users/mraible/quarkus/src/test/javascript/e2e/admin/administration.spec.ts:52:92
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/tslib/tslib.js:111:62)



[09:22:54] I/launcher - 0 instance(s) of WebDriver still running
[09:22:54] I/launcher - chrome #01 failed 2 test(s)
[09:22:54] I/launcher - overall: 2 failed spec(s)
[09:22:54] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blog@0.0.1-SNAPSHOT e2e: `protractor src/test/javascript/protractor.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blog@0.0.1-SNAPSHOT e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2020-12-10T16_22_54_701Z-debug.log
```

**Comment by avdev4j** [comment]
hi Matt,
this come from frontend admin pages we don't implement yet for Quarkus.

Metrics: We have micrometer metrics right now but the frontend is not able to display them
Logs: I don't have any idea of Logs status in Qaurkus, do we have any solution fo that. Otherwise we will need to disable this
Configuration: same as Logs

**Comment by avdev4j** [comment]
Close this ticket in favor of  #153
