### ISSUE TITLE
Okta + OAuth doesn't work

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#146]
**Describe the bug**

In the generated `README`, it says:

> The security settings in `src/main/resources/config/application.yml` are configured for this image.

This should be `src/main/resources/application.properties`.

I tried to configure a generated Quarkus app to work with Okta by modifying the following properties.

```
quarkus.oidc.auth-server-url=https://dev-6974382.okta.com/oauth2/default
%dev.quarkus.oidc.client-id=XXX
%dev.quarkus.oidc.credentials.secret=YYY

jhipster.oidc.logout-url=https://dev-6974382.okta.com/oauth2/default/v1/logout
```

I got these values by running the [Okta CLI](https://cli.okta.com) and selecting Web > JHipster. Then I copied the values from the generated `.okta.env` file.

I don't think it should be necessary to specify the `logout-url` since that can be looked up from the `./well-known/openid-configuration` endpoint. For example, see <https://dev-6974382.okta.com/oauth2/default/.well-known/openid-configuration> and look for the `end_session_endpoint`. This is the value we [use for Spring Security](https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/web/rest/LogoutResource.java.ejs#L62).

I started the app and when I tried to log in. This results in a "too many redirects" error, probably because `openid` isn't included as a scope.

![image](https://user-images.githubusercontent.com/17892/101804053-68271d80-3ace-11eb-9fd0-f612b8c02b8e.png)

I tried changing the scopes to the following and restarting.

```
quarkus.oidc.authentication.scopes=openid,profile,address,email,jhipster,microprofile-jwt,offline_access,phone
```

This results in:

```
http://localhost:8080/login/oauth2/code/oidc?state=bc8679ae-62f9-4c61-9179-8196f7a731c0&error=invalid_scope&error_description=One+or+more+scopes+are+not+configured+for+the+authorization+server+resource.
```

I tried removing the non-standard scopes:

```
quarkus.oidc.authentication.scopes=openid,profile,address,email,offline_access,phone
```

Same error. I believe this happens because "offline_access" is included and the Okta CLI doesn't configure a JHipster app to have refresh tokens. If I change the app to allow refresh tokens, it gets a bit further, but not much.

```
This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 401
```

The URL is http://localhost:8080/login/oauth2/code/oidc?code=Uri6Ddqqc-b-5ZlLRrs09_xMatccinT6iHYMrwbAi1M&state=b88c966b-711f-4310-b8f0-c6926253b2bc.

At one point, I did get a stack trace when it redirected back to my app, but now I'm not able to reproduce.

```
javax.enterprise.inject.CreationException: Synthetic bean instance for io.quarkus.oidc.runtime.TenantConfigBean not initialized yet: io_quarkus_oidc_runtime_TenantConfigBean_97d170e1550eee4afc0af065b78cda302a97674c
	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
	at io.quarkus.oidc.runtime.TenantConfigBean_db1a9da4c1df4426bbea69cb152051caf53ae9c3_Synthetic_Bean.create(TenantConfigBean_db1a9da4c1df4426bbea69cb152051caf53ae9c3_Synthetic_Bean.zig:117)
	at io.quarkus.oidc.runtime.TenantConfigBean_db1a9da4c1df4426bbea69cb152051caf53ae9c3_Synthetic_Bean.create(TenantConfigBean_db1a9da4c1df4426bbea69cb152051caf53ae9c3_Synthetic_Bean.zig:140)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.oidc.runtime.TenantConfigBean_db1a9da4c1df4426bbea69cb152051caf53ae9c3_Synthetic_Bean.get(TenantConfigBean_db1a9da4c1df4426bbea69cb152051caf53ae9c3_Synthetic_Bean.zig:172)
	at io.quarkus.oidc.runtime.TenantConfigBean_db1a9da4c1df4426bbea69cb152051caf53ae9c3_Synthetic_Bean.get(TenantConfigBean_db1a9da4c1df4426bbea69cb152051caf53ae9c3_Synthetic_Bean.zig:188)
	at io.quarkus.oidc.runtime.DefaultTenantConfigResolver_Bean.create(DefaultTenantConfigResolver_Bean.zig:682)
	at io.quarkus.oidc.runtime.DefaultTenantConfigResolver_Bean.create(DefaultTenantConfigResolver_Bean.zig:854)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at io.quarkus.oidc.runtime.DefaultTenantConfigResolver_ClientProxy.arc$delegate(DefaultTenantConfigResolver_ClientProxy.zig:67)
	at io.quarkus.oidc.runtime.DefaultTenantConfigResolver_ClientProxy.resolveConfig(DefaultTenantConfigResolver_ClientProxy.zig:183)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism.resolve(OidcAuthenticationMechanism.java:59)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism.authenticate(OidcAuthenticationMechanism.java:40)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism_ClientProxy.authenticate(OidcAuthenticationMechanism_ClientProxy.zig:189)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.attemptAuthentication(HttpAuthenticator.java:100)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:157)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:101)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:51)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterFilter.handle(VertxMeterFilter.java:28)
	at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterFilter.handle(VertxMeterFilter.java:14)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:47)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:336)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:332)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:412)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:409)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:126)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Resulted in: java.lang.RuntimeException: Error injecting io.quarkus.oidc.runtime.TenantConfigBean io.quarkus.oidc.runtime.DefaultTenantConfigResolver.tenantConfigBean
	at io.quarkus.oidc.runtime.DefaultTenantConfigResolver_Bean.create(DefaultTenantConfigResolver_Bean.zig:699)
	... 75 more
```

**Comment by mraible** [comment]
FWIW, I'm certain that Quarkus + OIDC _can_ work with Okta. See an example in [Secure Kafka Streams with Quarkus and Java](https://developer.okta.com/blog/2020/04/08/kafka-streams).

**Comment by danielpetisme** [comment]
Currently working on it, I'm confident!

Le ven. 11 déc. 2020 à 21:14, Matt Raible <notifications@github.com> a
écrit :

**Comment by mraible** [comment]
Fixed by #149.

**Comment by danielpetisme** [comment]
I propose to include the post to Okta's blog in the bounty.

@mraible @avdev4j  WDYT?

**Comment by mraible** [comment]
@danielpetisme I'm not sure what you mean. I think it's OK to claim the bounty before the post is live. That's a separate item, IMO.

**Comment by danielpetisme** [comment]
I was wondering to wait for the blog post publication before claiming the bounty...

But I think you're right the blog post isn't related to the current project so I'll claim the bounty as is
