### ISSUE TITLE
TypeError: jhContext.setupServerOptions is not a function

### ISSUE THREAD

**Issue by dalexandrov** [jhipster/generator-jhipster-quarkus#186]
Hello,
everytime I use `jhipster --blueprints quarkus`

and answer `? What is the base name of your application?`

```
ERROR! jhContext.setupServerOptions is not a function
TypeError: jhContext.setupServerOptions is not a function
    at new module.exports (/usr/local/lib/node_modules/generator-jhipster-quarkus/generators/server/index.js:22:19)
    at Environment.instantiate (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:748:23)
    at instantiate (/usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:1196:23)
    at module.exports.composeWith (/usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:1227:33)
    at module.exports.composeServer (/usr/local/lib/node_modules/generator-jhipster-quarkus/generators/app/index.js:107:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:976:25)
    at /usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:977:11)
Unhandled promise rejection at:
TypeError: jhContext.setupServerOptions is not a function
```
 

-   OS: Big Sur
-   JHipster: 7.7.6

**Comment by avdev4j** [comment]
Because you are using it with a JHipster 7. This blueprint is not compatible with JHipster 7 yet.
If you have installed the blueprint globally (through npm -g or npm link commands) I suggest you use `jhipster-quarkus` instead.
It will launch the right JHipster version (aka the one declared in the package.json blueprint).

**Comment by dalexandrov** [comment]
thank you!

**Comment by avdev4j** [comment]
You're welcome
