### ISSUE TITLE
Cannot use Blueprint on MacBookPro with M1

### ISSUE THREAD

**Issue by gerlicher** [jhipster/generator-jhipster-quarkus#217]
**Describe the bug**
When starting the blueprint after answering the first question "What is the base name of your application?" it crashes with the following error:

```
ERROR! jhContext.setupServerOptions is not a function
TypeError: jhContext.setupServerOptions is not a function
    at new module.exports (/opt/homebrew/lib/node_modules/generator-jhipster-quarkus/generators/server/index.js:22:19)
    at Environment.instantiate (/opt/homebrew/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:794:23)
    at instantiate (/opt/homebrew/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:1196:23)
    at module.exports.composeWith (/opt/homebrew/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:1227:33)
    at module.exports.composeServer (/opt/homebrew/lib/node_modules/generator-jhipster-quarkus/generators/app/index.js:107:22)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:976:25)
    at /opt/homebrew/lib/node_modules/generator-jhipster-quarkus/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /opt/homebrew/lib/node_modules/generator-jhipster-quarkus/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/opt/homebrew/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:977:11)
Unhandled promise rejection at:
TypeError: jhContext.setupServerOptions is not a function
```

**To Reproduce**

Running on this machine:

macOS Big Sur
Version 11.4

MacBook Pro (13", M1, 2020)
16 GB RAM

Installed JHipster using the npm description at: https://www.jhipster.tech/installation/

Java Version: 
openjdk version "11.0.9" 2020-10-20

npm version:
7.5.0

node version:
v15.8.0

1.  npm install -g generator-jhipster
2.  jhipster --blueprints quarkus 
3. The JHipster Quarkus Version displayed is v1.1.1
4.  Answer question: What is the base name of your application?
5. Error occurs

**Expected behavior**
Quarkus app generation should work

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser: n. a.
-   Version: 11.4

**Comment by avdev4j** [comment]
Hi @gerlicher,
This error occurs because you are using the last JHipster version (the default one that come with the npm installation - 7.1.0) but the blueprint only support the last JHipster 6 version.

You can try to install it by using "@6.10.5" when you install JHipster npm install -g generator-jhipster@6.10.5 or even better run the JHipster quarkus command to run both the blueprint and the right JHipster version: jhipster-quarkus


Please try and let me know

**Comment by gerlicher** [comment]
Hi @avdev4j,

thanks, very much. This solved the issue. It worked after installing the correct (old) hipster version.
But when trying to run the generated project with maven I now get the following error:

> Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
> You are running an incompatible version of Java. JHipster Quarkus supports JDK 8 to 13.

But my installed java version is: 11.0.9
This is what I get, when I run java --version:

> openjdk 11.0.9 2020-10-20
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

Do you have any idea, why this happens?

Thanks very much!
