### ISSUE TITLE
"ERROR! This is a JHipster blueprint and should be used only like jhipster --blueprint quarkus" 

### ISSUE THREAD

**Issue by karstengresch** [jhipster/generator-jhipster-quarkus#246]
**Describe the bug**
Running 

```
>jhipster --blueprints quarkus
```

results in the error message

```
>jhipster --blueprints quarkus
INFO! Using bundled JHipster
INFO! No custom sharedOptions found within blueprint: generator-jhipster-quarkus at /usr/local/lib/node_modules/generator-jhipster-quarkus
INFO! No custom commands found within blueprint: generator-jhipster-quarkus at /usr/local/lib/node_modules/generator-jhipster-quarkus
ERROR! This is a JHipster blueprint and should be used only like jhipster --blueprint quarkus
Error: This is a JHipster blueprint and should be used only like jhipster --blueprint quarkus
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/generator-jhipster/generators/generator-base.js:1590:15)
    at new module.exports (/usr/local/lib/node_modules/generator-jhipster-quarkus/generators/app/index.js:13:18)
    at Environment.instantiate (/Users/karsten/.nvm/versions/node/v12.22.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:806:23)
    at Environment.create (/Users/karsten/.nvm/versions/node/v12.22.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:778:17)
    at /Users/karsten/.nvm/versions/node/v12.22.1/lib/node_modules/generator-jhipster/cli/program.js:190:58
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async JHipsterCommand._lazyBuildCommandCallBack (/Users/karsten/.nvm/versions/node/v12.22.1/lib/node_modules/generator-jhipster/cli/program.js:180:13)
    at async JHipsterCommand._parseCommand (/Users/karsten/.nvm/versions/node/v12.22.1/lib/node_modules/generator-jhipster/cli/jhipster-command.js:79:7)
    at async JHipsterCommand.parseAsync (/Users/karsten/.nvm/versions/node/v12.22.1/lib/node_modules/generator-jhipster/node_modules/commander/lib/command.js:917:5)
```
Also w/o the 's' in 'blueprints', the behavior remains the same:

```
>jhipster --blueprint quarkus
INFO! Using bundled JHipster
INFO! No custom sharedOptions found within blueprint: generator-jhipster-quarkus at /Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster-quarkus
INFO! No custom commands found within blueprint: generator-jhipster-quarkus at /Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster-quarkus
(node:87742) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./lib/util/" in the "exports" field module resolution of the package at /Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json.
Update this package.json to use a subpath pattern like "./lib/util/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
ERROR! This is a JHipster blueprint and should be used only like jhipster --blueprint quarkus
Error: This is a JHipster blueprint and should be used only like jhipster --blueprint quarkus
    at module.exports.error (/Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster-quarkus/node_modules/generator-jhipster/generators/generator-base.js:1590:15)
    at new module.exports (/Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster-quarkus/generators/app/index.js:13:18)
    at Environment.instantiate (/Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:806:23)
    at Environment.create (/Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:778:17)
    at /Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster/cli/program.js:190:58
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async JHipsterCommand._lazyBuildCommandCallBack (/Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster/cli/program.js:180:13)
    at async JHipsterCommand._parseCommand (/Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster/cli/jhipster-command.js:79:7)
    at async JHipsterCommand.parseAsync (/Users/karsten/.nvm/versions/node/v16.17.1/lib/node_modules/generator-jhipster/node_modules/commander/lib/command.js:917:5)
```

**To Reproduce**

1.  Install latest JHipster, Yeoman and node LTS (here: 16.17.1, npm 8.15.0, yo 4.3.0)
2.  Run ```jhipster --blueprints quarkus```, alternatively ``` jhipster --blueprint quarkus```
3.  See error

**Expected behavior**
The "JHIPSTER QUARKUS" welcome screen appears and the interactive questionnaire session should begin.

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser: N/A
-   Version: N/A

**Additional context**
Just doesn't work and I have no further clue as even the error message doesn't make sense to me (the exact command was used).

I used a 12.x LTS version before and that failed w/ the same error.

**Comment by yacosta738** [comment]
same problem in Linux

![bitmoji](https://sdk.bitmoji.com/render/panel/4a737c47-e262-44e8-b96e-66d11bb30cab-db1ffc10-9e7f-4bea-a043-e744f59d5043-v1.png?transparent=1&palette=1&width=246)

**Comment by vishal423** [comment]
Can you try changes from below PR to see if that works for you?

https://github.com/jhipster/generator-jhipster-quarkus/pull/247

**Comment by yacosta738** [comment]
@vishal423 I try with #247 and it works perfectly. Thank you  👏

**Comment by avdev4j** [comment]
@yacosta738 I guess It's because you tried to use the blueprint with an unsupported version of JHipster. Downgrading the version of JHipster should work before vishal's work.

**Comment by karstengresch** [comment]
I tried w/ JHipster 7.9.3, latest quarkus blueprint and get:

```
jhipster --blueprints quarkus
INFO! Switching to JHipster installed locally in current project's node repository (node_modules)
INFO! No custom sharedOptions found within blueprint: generator-jhipster-quarkus at /Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/generator-jhipster-quarkus
INFO! No custom commands found within blueprint: generator-jhipster-quarkus at /Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/generator-jhipster-quarkus
INFO! Using bundled JHipster
INFO! No custom sharedOptions found within blueprint: generator-jhipster-quarkus at /Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/generator-jhipster-quarkus
INFO! No custom commands found within blueprint: generator-jhipster-quarkus at /Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/generator-jhipster-quarkus
(node:49651) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./lib/util/" in the "exports" field module resolution of the package at /Users/karsten/.nvm/versions/node/v16.18.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json.
Update this package.json to use a subpath pattern like "./lib/util/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
ERROR! undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/macos-release/index.js:27:26)
    at osName (/Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/os-name/index.js:21:18)
    at new Insight (/Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/insight/lib/index.js:37:13)
    at Statistics.configInsight (/Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/generator-jhipster/generators/statistics.js:60:25)
    at new Statistics (/Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/generator-jhipster/generators/statistics.js:50:14)
    at get (/Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/generator-jhipster/generators/statistics.js:249:27)
    at Object.<anonymous> (/Users/karsten/tmp/rh/c4d/202303_jh/second/node_modules/generator-jhipster/generators/statistics.js:255:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
```

Am I still supposed to do something manual to get the #247 changes on the machine? Or is this another issue?

**Comment by vishal423** [comment]
`v2.0.0` should fix the issue. Feel free to open a new issue if the error persists.
