### ISSUE TITLE
Not able to run this blueprint

### ISSUE THREAD

**Issue by ivanatdevoteam** [jhipster/generator-jhipster-quarkus#281]
when i try to run the command  "jhipster --blueprints quarkus" i get the following error. 

>INFO! Using bundled JHipster
INFO! No custom sharedOptions found within blueprint: generator-jhipster-quarkus at C:/Users/ig06152/AppData/Roaming/nvm/v16.19.1/node_modules/generator-jhipster-quarkus
INFO! No custom commands found within blueprint: generator-jhipster-quarkus at C:/Users/ig06152/AppData/Roaming/nvm/v16.19.1/node_modules/generator-jhipster-quarkus
(node:3556) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./lib/util/" in the "exports" field module resolution of the package at C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster\node_modules\yeoman-environment\package.json.
Update this package.json to use a subpath pattern like "./lib/util/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
ERROR! This is a JHipster blueprint and should be used only like jhipster --blueprint quarkus
Error: This is a JHipster blueprint and should be used only like jhipster --blueprint quarkus
    at module.exports.error (C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster-quarkus\node_modules\generator-jhipster\generators\generator-base.js:1590:15)
    at new module.exports (C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster-quarkus\generators\app\index.js:13:18)
    at Environment.instantiate (C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:806:23)
    at Environment.create (C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:778:17)
    at C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster\cli\program.js:190:58
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async JHipsterCommand._lazyBuildCommandCallBack (C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster\cli\program.js:180:13)
    at async JHipsterCommand._parseCommand (C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster\cli\jhipster-command.js:79:7)
    at async JHipsterCommand.parseAsync (C:\Users\ig06152\AppData\Roaming\nvm\v16.19.1\node_modules\generator-jhipster\node_modules\commander\lib\command.js:917:5)

node version is 16.9.1
npm version 8.19.3
java version 11.0.18

i think that this is the same issue as #246 but it was supposedly fixed with the merge of #247. I am still having the same issues

@vishal423 send help

**Comment by vishal423** [comment]
@ivanatdevoteam, can you please try against the `main` branch?

**Comment by ivanatdevoteam** [comment]
@vishal423 i installed the blueprint with the given command in the readme, im assuming it is using the main branch

**Comment by vishal423** [comment]
@ivanatdevoteam , you have to follow instructions listed under [this section](https://github.com/jhipster/generator-jhipster-quarkus#running-local-blueprint-version-for-development) of readme document. Let me know if that doesn't work.

**Comment by vishal423** [comment]
@ivanatdevoteam , Can you please try against recently published version `v2.0.0`? I will keep the ticket open for your confirmation.

**Comment by vishal423** [comment]
Closing the ticket as there is no response from the reporter. Feel free to comment if the issue is still reproducible.
