### ISSUE TITLE
ehcache caching option seems to not work

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-quarkus#336]
**Describe the bug**
With latest release 3.0.0, the ehcache provider seems to not work. Refer error below observed during sample app generation.

>ERROR! An error occured while running jhipster-quarkus:bootstrap-application#configuringTemplateTask
ERROR! ERROR! Cache provider ehcache is not supported
Error: Cache provider ehcache is not supported
    at default.configuringTemplateTask (file:///home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/generator-jhipster-quarkus/generators/bootstrap-application/generator.js:16:27)
    at default.executeTask (file:///home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/generator-jhipster-quarkus/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:26)
    at env.queueTask.once (file:///home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/generator-jhipster-quarkus/node_modules/yeoman-generator/dist/actions/lifecycle.js:218:56)
    at runLoop.add.once (file:///home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/generator-jhipster-quarkus/node_modules/yeoman-environment/dist/environment-base.js:384:23)
    at Immediate.<anonymous> (/home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/generator-jhipster-quarkus/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:478:21)
Error: Process completed with exit code 1.

**Comment by mraible** [comment]
Did it work in previous versions?

**Comment by diehmension** [comment]
This error still seems to exist with Version 3.2.0:
ERROR! An error occured while running jhipster-quarkus:bootstrap-application#configuringTemplateTask
ERROR! ERROR! Cache provider ehcache is not supported
Error: Cache provider ehcache is not supported
    at default.configuringTemplateTask (file:///usr/local/lib/node_modules/generator-jhipster-quarkus/generators/bootstrap-application/generator.js:16:27)
    at default.executeTask (file:///usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:26)
    at env.queueTask.once (file:///usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/dist/actions/lifecycle.js:218:56)
    at runLoop.add.once (file:///usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-environment/dist/environment-base.js:395:23)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-quarkus/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:483:21)
