### ISSUE TITLE
Error when generating a microservice application

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-quarkus#337]
**Describe the bug**

I was able to select `gateway` as an application type and generate an application. However, when I try to generate a microservice, I get an error:

```
ERROR! An error occured while running jhipster-quarkus:angular#customize
ERROR! ERROR! Unable to find /Users/mraible/Downloads/micro/src/main/webapp/app/admin/configuration/configuration.component.html.
Error: Unable to find /Users/mraible/Downloads/micro/src/main/webapp/app/admin/configuration/configuration.component.html.
    at default.editFile (file:///Users/mraible/.nvm/versions/node/v20.11.0/lib/node_modules/generator-jhipster-quarkus/node_modules/generator-jhipster/dist/generators/base-core/generator.mjs:799:23)
    at default.customize (file:///Users/mraible/.nvm/versions/node/v20.11.0/lib/node_modules/generator-jhipster-quarkus/generators/angular/generator.js:11:22)
    at default.executeTask (file:///Users/mraible/.nvm/versions/node/v20.11.0/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:26)
    at env.queueTask.once (file:///Users/mraible/.nvm/versions/node/v20.11.0/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/dist/actions/lifecycle.js:218:56)
    at runLoop.add.once (file:///Users/mraible/.nvm/versions/node/v20.11.0/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-environment/dist/environment-base.js:384:23)
    at Immediate.<anonymous> (/Users/mraible/.nvm/versions/node/v20.11.0/lib/node_modules/generator-jhipster-quarkus/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:478:21)
```

**To Reproduce**

? What is the base name of your application? micro
? Which *Framework* would you like to use for the client? Angular
? Besides Jest/Vitest, which testing frameworks would you like to use? Cypress
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Which *type* of application would you like to create? Microservice application
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to
 avoid port conflicts. 8081
? What is your default Java package name? com.mycompany.myapp
? Which *type* of authentication would you like to use? jwt
? Would you like to use Maven or Gradle for building the backend? Maven
? Which *type* of database would you like to use? SQL (SQL databases)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? Same as production
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install
? Would you like to generate code coverage for Cypress tests? [Experimental] Yes
? Would you like to audit Cypress tests? Yes

**Expected behavior**

A microservice app should be generated. 

**Screenshots**

<img width="1442" alt="Screenshot 2024-03-05 at 10 27 48 AM" src="https://github.com/jhipster/generator-jhipster-quarkus/assets/17892/72ecb79f-6afc-4a68-91f4-58ae5942cc43">

**Desktop (please complete the following information):**

-   OS: macOS

**Comment by mraible** [comment]
Closing because this isn't expected to work until this blueprint supports micro frontends. It works as expected when you accept the default of client = no.
